### ISSUE TITLE
Angular: support for urls in Waltz without using the # anchor

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#3567] opened 2018-11-09 15:32 UTC
This is to get around authentication proxies that may strip out all url characters after the #.

**Comment by davidwatkins73** [comment] 2018-11-14 05:44
Duplicate of: #2868 ?

**Comment by rovats** [comment] 2018-12-20 06:01
+1 This will be very useful

**Comment by kamransaleem** [comment] 2018-12-20 09:16
i think so yes.

**Comment by kamransaleem** [comment] 2018-12-20 09:20
#2868

**Closed** 2019-01-14 15:35 UTC
Labels: fixed (test & close), noteworthy
