### ISSUE TITLE
Data Type usage does not update after updating logical flow decorator

### ISSUE THREAD

**Issue by kamransaleem** [khartec/waltz#4380] opened 2019-09-30 15:21 UTC

**Comment by davidwatkins73** [comment] 2019-09-30 20:58
Duplicate of #4375

**Comment by kamransaleem** [comment] 2019-10-01 12:02
To isolate data_type_usages where there is no corresponding active logical flow:

```
select * from data_type_usage dtu
left outer join (
    select source_entity_kind as entity_kind,
    source_entity_id as entity_id,
    lfd.decorator_entity_id as data_type_id
    from logical_flow_decorator lfd
    inner join logical_flow lf on lfd.logical_flow_id = lf.id
    where lfd.decorator_entity_kind = 'DATA_TYPE'
    union
    select target_entity_kind as entity_kind,
    target_entity_id as entity_id,
    lfd.decorator_entity_id as data_type_id
    from logical_flow_decorator lfd
    inner join logical_flow lf on lfd.logical_flow_id = lf.id
    where lfd.decorator_entity_kind = 'DATA_TYPE'
    and lf.is_removed = false
      and lf.entity_lifecycle_status != 'REMOVED'
) sub on sub.entity_id = dtu.entity_id and sub.entity_kind = dtu.entity_kind and sub.data_type_id = dtu.data_type_id
where sub.entity_id is null
```

**Closed** 2019-11-28 08:54 UTC
Labels: bug, duplicate, fixed (test & close)
