### ISSUE TITLE
Duplicate key exception when creating lineage

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1760] opened 2017-03-03 10:46 UTC

**Comment by kamransaleem** [comment] 2017-03-03 10:47
10:27:32.052 [http-nio-11462-exec-1] ERROR com.khartec.waltz.web.Main - Exception: SQL [insert into [physical_flow_lineage] ([described_flow_id], [contributor_flow_id], [description], [last_updated_by]) values (?, ?, ?, ?)]; Violation of PRIMARY KEY constraint 'physical_flow_lineage_pkey'. Cannot insert duplicate key in object 'dbo.physical_flow_lineage'. The duplicate key value is (37058, 81014). / org.jooq.exception.DataAccessException
org.jooq.exception.DataAccessException: SQL [insert into [physical_flow_lineage] ([described_flow_id], [contributor_flow_id], [description], [last_updated_by]) values (?, ?, ?, ?)]; Violation of PRIMARY KEY constraint 'physical_flow_lineage_pkey'. Cannot insert duplicate key in object 'dbo.physical_flow_lineage'. The duplicate key value is (37058, 81014).
	at org.jooq.impl.Tools.translate(Tools.java:1690)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:659)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:354)
	at org.jooq.impl.TableRecordImpl.storeInsert0(TableRecordImpl.java:177)
	at org.jooq.impl.TableRecordImpl$1.operate(TableRecordImpl.java:143)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.TableRecordImpl.storeInsert(TableRecordImpl.java:139)
	at org.jooq.impl.UpdatableRecordImpl.store0(UpdatableRecordImpl.java:185)
	at org.jooq.impl.UpdatableRecordImpl.access$000(UpdatableRecordImpl.java:85)
	at org.jooq.impl.UpdatableRecordImpl$1.operate(UpdatableRecordImpl.java:135)
	at org.jooq.impl.RecordDelegate.operate(RecordDelegate.java:128)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:131)
	at org.jooq.impl.UpdatableRecordImpl.store(UpdatableRecordImpl.java:123)
	at com.khartec.waltz.data.physical_flow_lineage.PhysicalFlowLineageDao.addContribution(PhysicalFlowLineageDao.java:144)
	at com.khartec.waltz.service.physical_flow_lineage.PhysicalFlowLineageService.addContribution(PhysicalFlowLineageService.java:92)
	at com.khartec.waltz.web.endpoints.api.PhysicalFlowLineageEndpoint.addContribution(PhysicalFlowLineageEndpoint.java:165)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$4(EndpointUtilities.java:97)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.http.matching.Routes.execute(Routes.java:61)
	at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:127)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:173)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)
	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'physical_flow_lineage_pkey'. Cannot insert duplicate key in object 'dbo.physical_flow_lineage'. The duplicate key value is (37058, 81014).
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:216)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1515)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:404)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:350)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:5696)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:1715)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:180)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:155)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:314)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeUpdate(DefaultPreparedStatement.java:88)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:349)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:340)
	... 39 common frames omitted

**Comment by kamransaleem** [comment] 2017-03-03 15:06
This is related to #1764 

Caused when a lineage is created, attestation fail due to missing logical flow and client not updating to reflect a created lineage.

If a user clicks 'add' lineage again on the same flow, it will then attempt to insert and also existing lineage entry.  

Won't fix

**Closed** 2017-03-03 15:07 UTC
Labels: bug, wontfix
