### ISSUE TITLE
Perspectives: overrides not showing up on appview

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#1610] opened 2017-02-15 20:49 UTC
.... but only on one measurable:

![image](https://cloud.githubusercontent.com/assets/576829/22994731/ee3b15f2-f3bf-11e6-8ea6-88d370af8191.png)

Shows ok here:

![image](https://cloud.githubusercontent.com/assets/576829/22994775/0c19b696-f3c0-11e6-915e-edc864cd6219.png)

But now here (?):
![image](https://cloud.githubusercontent.com/assets/576829/22994819/3e371ef2-f3c0-11e6-94af-b34bdcdd47b7.png)

Application: 80

**Comment by kamransaleem** [comment] 2017-02-17 12:15
This is working exactly as I would expect...
Have cross-checked the values on both axes, seem accurate, sample below.


![image](https://cloud.githubusercontent.com/assets/3029467/23064904/a40bb986-f50a-11e6-95a6-479d8eede249.png)


![image](https://cloud.githubusercontent.com/assets/3029467/23064919/b2c3b6d6-f50a-11e6-870b-20d5747b7ca4.png)

**Comment by davidwatkins73** [comment] 2017-02-17 12:20
yeah - I haven't detected the pattern to breakages yet.  It usually only fails when looking at the data from one of the perspectives axis..  i.e. in your example  switching to the `Process` tab and selecting `Client Reporting` may show the indicator (*) but not the detail (that it is overriden by the `Enterprise Control` function with 'R'

**Comment by davidwatkins73** [comment] 2017-02-17 12:21
Oh - just re-read your first line.  You've already checked this scenario...

**Comment by kamransaleem** [comment] 2017-02-17 12:27
ok, managed to reproduce it consistently.  Not entirely sure of the changes I made though.

Will step through the code to see what's wrong.

**Comment by davidwatkins73** [comment] 2017-02-17 12:33
good luck - bit gnarly in there.

**Comment by kamransaleem** [comment] 2017-02-17 14:33
Ok, found the issue.  It seems to hide it when the perspective override has the same rating as the measurable.  If you change it from the measurable then it will show the perspective override, see example below:

![image](https://cloud.githubusercontent.com/assets/3029467/23069068/ed233d02-f51d-11e6-9ff6-b4c1a088fb89.png)


What is the best fix for this?  Show the override even though it is the same rating or hide it?  My opinion is to show because although the value looks the same, it is for a specific context i.e. that perspective when paired with another measurable and hence should be shown.  

Thoughts?

**Comment by kamransaleem** [comment] 2017-02-17 15:35
have checked in a fix which doesn't hide any overrides, review and let me know your thoughts.  The other option would be to only show the overrides section if after the overrides are filters the count > 0 and also hide the * if not.

**Comment by davidwatkins73** [comment] 2017-02-17 16:11
Will have a play - I remember writing the code to hide the 'redundant' results now.  Think I intended to hide the indicator (*) in that case.  However take your point that it may be useful to emphasise the result.

**Closed** 2017-02-21 17:33 UTC
Labels: bug, fixed (test & close), priority ticket
