### ISSUE TITLE
Exception thrown when rebuilding hierarchy

### ISSUE THREAD

**Issue by davidwatkins73** [khartec/waltz#593] opened 2016-09-26 14:07 UTC
```
13:06:40.154 [http-nio-12792-exec-5] DEBUG c.k.w.w.e.a.HeaderBasedAuthenticationFilter - User according to header: rohit.vats@db.com
13:06:51.619 [http-nio-12792-exec-3] DEBUG c.k.w.w.e.a.HeaderBasedAuthenticationFilter - User according to header: rohit.vats@db.com
13:06:51.641 [http-nio-12792-exec-3] INFO  c.k.w.w.e.a.EntityHierarchyEndpoint - Building entity hierarchy for kind: CHANGE_INITIATIVE
13:06:52.066 [http-nio-12792-exec-3] ERROR com.khartec.waltz.web.Main - Exception: null / java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.streamSelf(EntityHierarchyService.java:172)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.lambda$streamItemsForNode$77(EntityHierarchyService.java:164)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1620)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.convertFlatNodesToHierarchyItems(EntityHierarchyService.java:157)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.buildFor(EntityHierarchyService.java:122)
	at com.khartec.waltz.service.entity_hierarchy.EntityHierarchyService.buildFor(EntityHierarchyService.java:116)
	at com.khartec.waltz.web.endpoints.api.EntityHierarchyEndpoint.buildByKindRoute(EntityHierarchyEndpoint.java:65)
	at com.khartec.waltz.web.endpoints.EndpointUtilities.lambda$wrapDatumHandler$3(EndpointUtilities.java:95)
	at spark.ResponseTransformerRouteImpl$1.handle(ResponseTransformerRouteImpl.java:47)
	at spark.webserver.MatcherFilter.doFilter(MatcherFilter.java:162)
	at spark.servlet.SparkFilter.doFilter(SparkFilter.java:122)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.StuckThreadDetectionValve.invoke(StuckThreadDetectionValve.java:206)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.ha.session.JvmRouteBinderValve.invoke(JvmRouteBinderValve.java:192)
	at org.apache.catalina.ha.tcp.ReplicationValve.invoke(ReplicationValve.java:318)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1099)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:670)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by kamransaleem** [comment] 2016-09-27 14:19
fixed in client db log file, caused by change initiatives with missing parent ids.

Also added change initiatives to orphan view to help spot more easily in future

**Closed** 2016-09-27 16:20 UTC
Labels: bug, fixed (test & close)
